name: TestingBuild

on:
  schedule:
    # This is a UTC time
    - cron: "0 16 * * *"
  # Keep it only for test purpose, comment it once everything is ok
  workflow_dispatch:

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: ks-installer
  IMAGE_REPO: sagilio
  IMAGE_VERSION: latest

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.repository	== 'sagilio/ks-installer'
    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: |
          tag=testing-$(date '+%Y%m%d%H%M')
          sed -i "2idev_tag\: $tag" roles/download/defaults/main.yml
          docker build . --file Dockerfile --tag $IMAGE_NAME

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=$IMAGE_REPO/$IMAGE_NAME
          
          tag=testing-$(date '+%Y%m%d%H%M')

          docker tag $IMAGE_NAME $IMAGE_ID:${tag}
          docker tag $IMAGE_NAME $IMAGE_ID:latest
          docker push $IMAGE_ID:${tag}
          docker push $IMAGE_ID:latest
